Ruby 2.2 doesn't work on Travis any more
   $ gem install bundler
   ERROR:  Error installing bundler:
   	bundler requires Ruby version >= 2.3.0.
   The command "gem install bundler" failed and exited with 1 during .